<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-08T17:01:49 IST" name="Default suite" finished-at="2024-02-08T17:02:52 IST" duration-ms="63069">
    <groups>
    </groups>
    <test started-at="2024-02-08T17:01:49 IST" name="Default test" finished-at="2024-02-08T17:02:52 IST" duration-ms="63069">
      <class name="com.Getapcs.Avision.TEST.TEST_SA_Flow">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.Getapcs.Avision.TEST.TEST_SA_Flow@2826f61]" started-at="2024-02-08T17:01:49 IST" name="setUp" finished-at="2024-02-08T17:01:57 IST" duration-ms="7560" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyPOcreate$Approvals_1_2()[pri:16, instance:com.Getapcs.Avision.TEST.TEST_SA_Flow@2826f61]" started-at="2024-02-08T17:01:57 IST" name="verifyPOcreate$Approvals_1_2" finished-at="2024-02-08T17:02:52 IST" duration-ms="55090" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect [https://avision-demo.getapcs.com/transaction/purchase-order/create] but found [https://avision-demo.getapcs.com/transaction/purchase-order/create]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect [https://avision-demo.getapcs.com/transaction/purchase-order/create] but found [https://avision-demo.getapcs.com/transaction/purchase-order/create]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failEquals(Assert.java:1582)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:157)
at org.testng.Assert.assertNotEquals(Assert.java:2201)
at org.testng.Assert.assertNotEquals(Assert.java:2223)
at com.Getapcs.Avision.Transaction.Purchase_Order_SA2.purchaseOrderCreatePage(Purchase_Order_SA2.java:458)
at com.Getapcs.Avision.TEST.TEST_SA_Flow.verifyPOcreate$Approvals_1_2(TEST_SA_Flow.java:724)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPOcreate$Approvals_1_2 -->
        <test-method is-config="true" signature="getTestResult(org.testng.ITestResult)[pri:0, instance:com.Getapcs.Avision.TEST.TEST_SA_Flow@2826f61]" started-at="2024-02-08T17:02:52 IST" name="getTestResult" finished-at="2024-02-08T17:02:52 IST" duration-ms="17" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyPOcreate$Approvals_1_2 status=FAILURE method=TEST_SA_Flow.verifyPOcreate$Approvals_1_2()[pri:16, instance:com.Getapcs.Avision.TEST.TEST_SA_Flow@2826f61] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestResult -->
        <test-method is-config="true" signature="afetrTest()[pri:0, instance:com.Getapcs.Avision.TEST.TEST_SA_Flow@2826f61]" started-at="2024-02-08T17:02:52 IST" name="afetrTest" finished-at="2024-02-08T17:02:52 IST" duration-ms="362" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afetrTest -->
      </class> <!-- com.Getapcs.Avision.TEST.TEST_SA_Flow -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
